### Request 1  (GET) from browser

GET http://localhost:3000/

### Request 2 (POST) in signin

POST http://localhost:3000/signin
content-type: application/json

{
    "email" : "sally@gmail.com",
    "password" : "bananas"
}

### Request 3 (POST) in register

POST http://localhost:3000/register  HTTP/1.1
content-type: application/json

{
    "name" : "yaya",
    "email" : "yaya@gmail.com",
    "password" : "yaya123"

}

### Request 4 (POST) in register

POST http://localhost:3000/register  HTTP/1.1
content-type: application/json

{
    "name" : "sally",
    "email" : "sally@gmail.com",
    "password" : "bananas"
}

